name: PrimPlugin
version: 1.0
main: tech.nully.primplug.Main
authors: [BongoCat, ayonull]
api-version: 1.5.2
description: A custom coded plugin for primcraft
website: "https://nully.tech"
commands:
  getp:
    description: Gives the user a Petherite chestplate
    usage: /<command>
  getbod:
    description: Gives the user a curse of despair
    usage: /<command>